src/Entity/Profil.php
<?php

namespace App\Entity;

use App\Repository\ProfilRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=ProfilRepository::class)
 */
class Profil
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date")
     */
    private $dateNaissance;

    /**
     * @ORM\Column(type="string", length=15)
     */
    private $sexe;

    /**
     * @Assert\Length(
     *     min=5,
     *     max=5
     * )
     * @ORM\Column(type="integer")
     */
    private $CodePostal;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Ville;

    /**
     * @ORM\OneToOne(targetEntity=User::class, inversedBy="profil", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\OneToMany(targetEntity=PhotoProfil::class, mappedBy="profil")
     */
    private $PhotoProfils;

    /**
     * @ORM\ManyToOne(targetEntity=Critere::class, inversedBy="profils")
     */
    private $criteres;

    public function __construct()
    {
        $this->PhotoProfils = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->dateNaissance;
    }

    public function setDateNaissance(\DateTimeInterface $dateNaissance): self
    {
        $this->dateNaissance = $dateNaissance;

        return $this;
    }

    public function getSexe(): ?string
    {
        return $this->sexe;
    }

    public function setSexe(string $sexe): self
    {
        $this->sexe = $sexe;

        return $this;
    }

    public function getCodePostal(): ?int
    {
        return $this->CodePostal;
    }

    public function setCodePostal(int $CodePostal): self
    {
        $this->CodePostal = $CodePostal;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->Ville;
    }

    public function setVille(string $Ville): self
    {
        $this->Ville = $Ville;

        return $this;
    }
    

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection|PhotoProfil[]
     */
    public function getPhotoProfils(): Collection
    {
        return $this->PhotoProfils;
    }

    public function addPhotoProfil(PhotoProfil $photoProfil): self
    {
        if (!$this->PhotoProfils->contains($photoProfil)) {
            $this->PhotoProfils[] = $photoProfil;
            $photoProfil->setProfil($this);
        }

        return $this;
    }

    public function removePhotoProfil(PhotoProfil $photoProfil): self
    {
        if ($this->PhotoProfils->removeElement($photoProfil)) {
            // set the owning side to null (unless already changed)
            if ($photoProfil->getProfil() === $this) {
                $photoProfil->setProfil(null);
            }
        }

        return $this;
    }

    public function getCriteres(): ?Critere
    {
        return $this->criteres;
    }

    public function setCriteres(?Critere $criteres): self
    {
        $this->criteres = $criteres;

        return $this;
    }
    
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Pseudo;

    /**
     * @ORM\OneToOne(targetEntity=Profil::class, mappedBy="user", cascade={"persist", "remove"})
     */
    private $profil;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getPseudo(): ?string
    {
        return $this->Pseudo;
    }

    public function setPseudo(string $Pseudo): self
    {
        $this->Pseudo = $Pseudo;

        return $this;
    }

    public function getProfil(): ?Profil
    {
        return $this->profil;
    }

    public function setProfil(Profil $profil): self
    {
        // set the owning side of the relation if necessary
        if ($profil->getUser() !== $this) {
            $profil->setUser($this);
        }

        $this->profil = $profil;

        return $this;
    }
}

src/Form/ProfilType.php
<?php

namespace App\Form;

use App\Entity\Profil;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProfilType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('dateNaissance', DateType::class, [
                'widget' => 'single_text'
            ])
            ->add('sexe', ChoiceType::class, [
                'choices' => [
                    'Femme' => 'Femme',
                    'Homme' => 'Homme',
                    'Non-Binaire' => 'Non-Binaire'
                ]
            ])
            ->add('CodePostal')
            ->add('Ville')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Profil::class,
        ]);
    }
}

src/Controller/ProfilController.php
<?php

namespace App\Controller;

use App\Entity\Critere;
use App\Entity\PhotoProfil;
use App\Entity\Profil;
use App\Entity\User;
use App\Form\CritereType;
use App\Form\ModifierProfilType;
use App\Form\PhotoProfilType;
use App\Form\ProfilType;
use App\Repository\CritereRepository;
use App\Repository\PhotoProfilRepository;
use App\Repository\ProfilRepository;
use App\Repository\UserRepository;
use Cassandra\Type\UserType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\ByteString;
use function Sodium\add;

class ProfilController extends AbstractController
{

    /**
     * @Route("/detail/{id}", name="profil_detail")
     */

    public function detail(int $id, ProfilRepository $profilRepository) {

        return $this->render('profil/detail.html.twig', [
            "profil" => $profilRepository->find($id)
        ]);
    }

    /**
     * @Route("/ajoutPhoto", name="profil_ajoutPhoto")
     */

    public function ajoutPhoto(Request $request, EntityManagerInterface $manager) {

        //on récupère le user connecté
        /** @var User $user */
        $user = $this->getUser();
        $userId = $this->getUser()->getProfil()->getId();

        //on instancie une photo de profil
        $photoProfil = new PhotoProfil();

        //création d'un formulaire pour ajouter la photo de profil !
        $photoForm = $this->createForm(PhotoProfilType::class, $photoProfil);
        $photoForm->handleRequest($request);

        if($photoForm->isSubmitted() && $photoForm->isValid()) {

            /** @var UploadedFile $telechargementPhoto */
            $telechargementPhoto = $photoForm->get('file')->getData();
            $nouveauNomPhoto = ByteString::fromRandom(30). '.' .$telechargementPhoto->guessExtension();

            try {
                $telechargementPhoto->move(__DIR__.'/../../public/profile/img', $nouveauNomPhoto);
            } catch(\Exception $e) {
                dd($e->getMessage());
            }

            $photoProfil->setDateCreation(new \DateTime());
            $photoProfil->setProfil($user->getProfil());
            $photoProfil->setNomFichier($nouveauNomPhoto);

            $manager->persist($photoProfil);
            $manager->flush();

            $this->addFlash('success', 'Merci pour la/les photo(s)! ');


            if($user->getProfil()->getCriteres()) {
                return $this->redirectToRoute('profil_detail', [
                    'id' => $userId
                ]);
            }

            return $this->redirectToRoute('profil_critere');
        }

        return $this->render('profil/ajoutPhoto.html.twig', [
            'photoForm' => $photoForm->createView()
        ]);
    }

    /**
     * @Route("/critere", name="profil_critere")
     */

    public function critere(Request $request, EntityManagerInterface $entityManager) {

        /** @var User $user */
        $user = $this->getUser();

        $critere = new Critere();
        $critereForm = $this->createForm(CritereType::class, $critere);
        $critereForm->handleRequest($request);

        if ($critereForm->isSubmitted() && $critereForm->isValid()) {

                $critere->addProfil($user->getProfil());
                $entityManager->persist($critere);
                $entityManager->flush();

                $this->addFlash('success', 'Critères bien ajoutés à votre profil ! ');
                return $this->redirectToRoute('main_home');

        }

        return $this->render('profil/ajoutCritere.html.twig', [
            'critereForm' => $critereForm->createView()
        ]);
    }


    //Controler si l'utilisateur connecté à un profil ou non afin de le rediriger vers les bonnes pages.
    /**
     * @Route("/profil", name="profil_controller")
     */

    public function profilController(){

        //on récupère le user connecté
        /** @var User $user */
        $user = $this->getUser();

        //si l'utilisateur a déjà un profil, on le redirige vers le détail de son profil
        if($user->getProfil()) {
            //on récupère l'id du profil de l'utilisateur connecté
            $userProfilId = $user->getProfil()->getId();
            return $this->redirectToRoute('profil_detail', [
                'id' => $userProfilId
            ]);

        //sinon on le redirige vers la page de création de profil !
        } else {
            return $this->redirectToRoute('profil_create');
        }

    }

/*    /**
     * @Route("/suggestions", name="profil_suggestions")
     */

    public function suggestions(ProfilRepository $profilRepository, CritereRepository $critereRepository){
        //on récupère le user connecté
        /** @var User $user */
        $user = $this->getUser();
        $userId = $user->getProfil()->getId();
        if($user->getProfil()->getCriteres()){

            //on récupère les critères de l'utilisateur connecté
            $critereUtilisateur =$user->getProfil()->getCriteres();

            $profils = $profilRepository->recupereCriteresCorrespondantsAuUser($critereUtilisateur);


            if($profils) {
                return $this->render('profil/suggestions.html.twig', [
                    'criteresCorrespondants' => $profils
                ]);
            } else {
                $this->addFlash('warning', "Désolé, vous n'avez aucune suggestion");
            }

        } else {
            $this->addFlash('warning', "Vous n'avez pas de suggestions, veuillez renseigner vos critères");
            return $this->redirectToRoute('profil_critere');
        }
        return $this->render('profil/suggestions.html.twig');
    }

    /**
     * @Route("/modifierProfil", name="profil_modifier_profil")
     */

    public function modifierProfil(ProfilRepository $profilRepository,
                                   EntityManagerInterface $manager,
                                   Request $request){

        //Je récupère le profil de l'utilisateur connecté
        $profil = $this->getUser()->getProfil();

        //je crée le form et j'associe mon formulaire et mon profil ensemble
        $form = $this->createForm(ProfilType::class, $profil);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {

                $manager->persist($profil);
                $manager->flush();

            $this->addFlash('success', 'Profil modifié ! ');

                return $this->redirectToRoute('main_home');
        }

            return $this->render('profil/modifierProfil.html.twig', [
                'modifForm' => $form->createView()
            ]);
    }



    /**
     * @Route("/modifierCritere", name="profil_modifier_critere")
     */

    public function modifierCritere(CritereRepository $critereRepository,
                                    EntityManagerInterface $manager,
                                    Request $request){

        //Je récupère le profil de l'utilisateur connecté
        $profil = $this->getUser()->getProfil();

        //Je récupère l'id du critère de l'utilisateur connecté
        $critere = $this->getUser()->getProfil()->getCriteres();

        //je récupère les critères de l'utilisateur connecté avec l'id critère
        $criteres =  $critereRepository->find($critere);

        //je crée le formulaire en associant le formulaire Critère et les critères
        $form = $this->createForm(CritereType::class, $criteres);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {

            $profil->setCriteres($criteres);

            $manager->persist($profil);
            $manager->flush();

            $this->addFlash('success', 'Critères modifiés ! ');

            return $this->redirectToRoute('main_home');
        }

        return $this->render('profil/modifierCritere.html.twig', [
            'modifForm' => $form->createView()
        ]);
    }


    /**
     * @Route("/create", name="profil_create")
     */
    public function create(Request $request,
                           EntityManagerInterface $manager,
                           UserRepository $userRepository): Response
    {

        // Récupère l'utilisateur connecté
        /** @var User $user */
        $user = $this->getUser();

        // Récupère l'utilisateur connecté
        $user = $this->getUser();

        // Récupère les infos de l'utilisateur connecté
        $result = $userRepository->find($user);

        // Si l'utilisateur a déjà un profil, on le redirige avec un message flash
        if ($result->getProfil()) {
            $this->addFlash('warning', 'Vous avez déjà un profil');
            return $this->redirectToRoute('main_home');
        }
        // Sinon, on affiche le formulaire et on crée le profil
        else {
            $profil = new Profil();
            $profil->setUser($user);

            $profilForm = $this->createForm(ProfilType::class, $profil);
            $profilForm->handleRequest($request);

            if($profilForm->isSubmitted() && $profilForm->isValid()) {
                $manager->persist($profil);
                $manager->flush();

                $this->addFlash('success', 'Bienvenue chez LoveNest ! ');
                return $this->redirectToRoute('profil_ajoutPhoto');

            }

            return $this->render('profil/create.html.twig', [
                "profileForm" =>$profilForm->createView()
            ]);
        }

    }


}

templates/profil/ajoutCritere.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container mt-4">

        {{ form_start(critereForm) }}
        {{ form_widget(critereForm) }}
        <button class="btn-success btn mt-2">Valider

        {{ form_end(critereForm)}}
    </div>

{% endblock %}

{% block title %}

{% endblock %}

templates/profil/ajoutCritère.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container mt-4">
        {{ form(critereForm) }}
        <div>Pouic</div>
    </div>

{% endblock %}

{% block title %}

{% endblock %}

templates/profil/ajoutPhoto.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<div class="container">

<h1 class="mb-2">Choisis ta photo</h1>
    {{ form_start(photoForm) }}
    {{ form_widget(photoForm) }}
    <button class="btn-success btn mt-2">Envoyer ma photo</button>
    {{ form_end(photoForm) }}
</div>
{% endblock %}

{% block title %}

{% endblock %}

templates/profil/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}Créer ton profil{% endblock %}

{% block body %}
    {% for flashError in app.flashes('verify_email_error') %}
        <div class="alert alert-danger" role="alert">{{ flashError }}</div>
    {% endfor %}

    <div class="container">
    <h1>Qui es-tu?</h1>

    {{ form_start(profileForm) }}
    {{ form_widget(profileForm) }}
    <button type="submit" class="btn btn-success mt-2">Créer mon profil</button>
    {{ form_end(profileForm) }}

    </div>
{% endblock %}

templates/profil/detail.html.twig
{% extends 'base.html.twig' %}

{% block title %}Détail{% endblock %}

{% block body %}

    <div class="container mt-4 ">
        <div class="row">
            <div class="col-4">

                    {% for photo in profil.photoProfils %}
                        <img class="mb-4" alt="photo" src="../profile/img/{{ photo.nomFichier }}">
                    {% endfor %}

            </div>

            <div class="col-4">
                <h1>Profil de {{ profil.user.pseudo }}</h1>
                    <p>Pseudo : {{ profil.user.pseudo }}</p>
                    <p>Date de naissance : {{ profil.dateNaissance|date('d/m/Y') }}</p>
                    <p>Sexe : {{ profil.sexe }}</p>
                    <p>Ville : {{ profil.ville }}</p>
                    <p>Code Postal : {{ profil.codePostal }}</p>
                    <a href="{{ path('profil_modifier_profil', {id:app.user.profil.id}) }}" class="btn btn-success">Modifier mon profil</a>
                {% if app.user.profil.photoProfils %}
                    <a href="{{ path('profil_ajoutPhoto') }}" class="btn btn-success">Ajouter une photo</a>
                {% endif %}
            </div>

            <div class="col-4">

                {% if(app.user.profil.criteres) %}

                <h1>Critères</h1>
                    <div>Sexe recherché : {{ profil.criteres.sexesRecherches }}</div>
                    <div>Age recherché minimum: {{ profil.criteres.ageRecherchesMin }}</div>
                    <div>Age recherché maximum: {{ profil.criteres.ageRecherchesMax }}</div>

                    <div>Département recherché : {{ profil.criteres.departementsRecherches }}</div>
                    <a href="{{ path('profil_modifier_critere', {id:app.user.profil.id}) }}" class="btn btn-success">Modifier mes critères</a>

                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

templates/profil/modifierCritere.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <div class="container">
        {{ form_start(modifForm) }}
        {{ form_widget(modifForm) }}
        <button class="btn-success btn mt-2">Modifier</button>

        {{ form_end(modifForm) }}
    </div>

{% endblock %}

{% block title %}

{% endblock %}

templates/profil/modifierProfil.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <div class="container">
        {{ form_start(modifForm) }}
        {{ form_widget(modifForm) }}
        <button class="btn-success btn mt-2">Sauvegarder</button>
        {{ form_end(modifForm) }}
    </div>
{% endblock %}

{% block title %}

{% endblock %}

templates/profil/suggestions.html.twig
{% extends 'base.html.twig' %}

{% block body %}

<div class="container">
    <h1>Mes suggestions</h1>

    <div class="row">
        <div class="col-md-3">
    {% for profil in criteresCorrespondants %}
        {% if profil.id != app.user.profil.id %}



                <div class="card mt-3 mb-3" style="width: 18rem;">
                    {% if(profil.PhotoProfils()) %}

                    {% for photo in profil.PhotoProfils  %}
                        <img class="card-img-top" src="./profile/img/{{ photo.nomFichier }}"
                             width="20" height="400" alt="photoProfil">
                    {% endfor %}
                {% else %}
                        <img class="card-img-top" src="https://picsum.photos/200/300" alt="Card image cap">
                {% endif%}


                <div class="card-body mt-3 mb-3">
                    <h5 class="card-title"><a href="{{ path('profil_detail', {id:profil.id}) }}">{{ profil.user.pseudo }}</a></h5>
                    <div class="card-text">
                        <p>{{ profil.sexe }}</p>
                        <p>{{ profil.ville }}</p>
                        <p>{{ profil.dateNaissance|date('d/m/Y') }}</p>
                    </div>
                    <a href="{{ path('profil_detail', {id:profil.id}) }}" class="btn btn-primary">
                        Voir le profil
                    </a>
                    <input type="hidden" id="profil_id" value="{{ profil.id }}">
                </div>
            </div>
        {% endif %}
    {% endfor %}
        </div>
    </div>
</div>


{% endblock %}

{% block title %}

{% endblock %}